### ISSUE TITLE
Planning to allow manually specified non-CRAN packages?

### ISSUE THREAD

**Issue by skranz** [r-universe-org/roadmap#39]
I just found out about and tested r-universe and it seems like a fantastic service. Thanks a lot! I wonder whether there are plans to allow universes that contain packages that are neither on CRAN nor listed in a Remotes field of a CRAN package?

Personally, I would find it great to have the opportunity to automatically build and host binaries for Windows and Mac in a repository where on is responsible for one own's quality control. While being on CRAN is clearly a quality signal, I believe there are also benefit for such non-CRAN universes as alternatives, e.g. in cases where time constraints prevent developers to maintain all packages according to CRAN standards.

PS: I must admit that I already tried to game the system by temporarily adding another packages in the Remotes field in the Github version of my one package on CRAN. But once I removed the package from the Remotes fields it got removed again from r-universe... so no success with that work-around attempt.

**Comment by jeroen** [comment]
Yes we plan to soon allow you to control your own registry file. If you want I can opt you in right now, you need to create a registry like this: https://github.com/gadenbuie/universe/

**Comment by skranz** [comment]
That's great! 

There is no problem for me waiting until the service becomes generally available. That being said, I indeed would be curious testing the functionality and thus created such a repo here: https://github.com/skranz/universe

**Comment by jeroen** [comment]
OK I have switched your universe to your own registry. Use it wisely ;) 
Lmk if you have any problems or suggestions.
