### ISSUE TITLE
Opt-out feature?

### ISSUE THREAD

**Issue by eddelbuettel** [r-universe-org/roadmap#46]
Could you support an option to unlist repos, orgs, or maintainers from r-universe?

(Originally filed on March 4 as issue number 2 in the cran-to-git repo but appears to have been deleted without comment.)

**Comment by jeroen** [comment]
Your other issue is literally 7 lines below this one.

**Comment by eddelbuettel** [comment]
My apologies. I had had coffee and I looked for minutes and did not find it.
